#!/bin/bash
#
# Copyright 2025 Telefonaktiebolaget LM Ericsson
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

SCRIPT_DIR=$(cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)
export PYTHONPATH="$PYTHONPATH:${SCRIPT_DIR}/src/bin"

if [ -z "${CI}" ]; then
  echo "Installing virtualenv"
  pip install --user virtualenv
  virtualenv "${SCRIPT_DIR}/target/venv" --python=python3
  source "${SCRIPT_DIR}/target/venv/bin/activate"
fi

pip install sphinx
pip install sphinxcontrib-autoprogram
pip install sphinxnotes-markdown-builder

sphinx-build -M markdown ${SCRIPT_DIR}/src ${SCRIPT_DIR}/target/
sed -i 's:<:\&lt;:g' ${SCRIPT_DIR}/target/markdown/index.md
sed -i 's:>:\&gt;:g' ${SCRIPT_DIR}/target/markdown/index.md
cp ${SCRIPT_DIR}/target/markdown/index.md ${SCRIPT_DIR}/../docs/autogenerated/ECCTOOL.md
